### PR TITLE
Upgrade to Guzzle 6

### PR DESCRIPTION
**Pull request by supersmile2009**
A long awaited rewrite to get rid of Guzzle 3, addressing issue #2.

Pros:
- Upgraded everything to work Guzzle 6.
- Reformatted code according to PSR.
- Cleaned-up garbage/deprecated stuff
- Fixed and improved unit tests. Fixed weird tests inheritance, which caused test cases of one the tests (parent) to run multiple times (when running a child test). There's still room for improvement though - I don't think these tests should send any live requests. Requirement to set up a project with all necessary locales, API key etc. just to run the tests is insane. Those are more of an API tests and not SDK library tests. However I don't have any plans to rewrite those tests now with mocked responses.
- Minimum of breaking changes. All responses (except for special response classes) will be instances of `GuzzleHttp\Command\Result` instead of `Guzzle\Service\Resource\Model`. And of course old Guzzle exceptions were replaced by new ones. But that's pretty much it, unless you used old ApiClient in some weird ways.
- Nice and readable code style
Cons:
- Old PHPUnit version and PHP 5.5+. However if you wish to drop all of that ancient stuff, I'll be happy to drop PHP 5 support and upgrade it to PHP 7+ only.

You need to merge https://github.com/loco/swizzle/pull/4 first and tag it as v2.0.0, because this PR already requires Swizzle v2.

### CODE REVIEW

**Comment by timwhitlock** [comment]
Thanks again for this. I'm trying it out now.

> Requirement to set up a project with all necessary locales, API key etc. just to run the tests is insane. Those are more of an API tests and not SDK library tests. 

I agree. The tests **were** originally doubling as tests for the API, but that is no longer the case and in fact became a pain.

**Comment by timwhitlock** [comment]
Just one question so far after testing this out ..

What was the reason for changing the expected structure of the `config.json` file? I need a good reason to break people's existing setups when they upgrade. If it's just personal preference, then I'll have to reinstate the previous format. If it's necessary for Guzzle 6 then can you let me know?

Thanks.

**Comment by supersmile2009** [comment]
This is a config required by guzzle-services. It doesn't support primitive return types anymore as well as arrays of anything defined right in operation. It only supports "returnModel" config option, which should be a valid model from the "models" section.

Deserilizing into a custom class isn't supported by guzzle-services, so "class" properties in some of the models are handled by that's why

**Comment by supersmile2009** [comment]
Sorry, was typing from my phone and accidentally closed the PR. 
Deserilizing into custom class is handled by Deserializer class and config options I'm using for it is something I had to come up with myself. I'll make a PR to guzzle-services later to add this feature back. When they split guzzle into separate projects, they dropped this feature and never re-implemented it again, however there are feature requests in guzzle-services repo to add this feature back.

**Comment by timwhitlock** [comment]
I'm not referring to the "class" option. I get that part, and that's fine. I mean the JSON config that holds API key etc.. You even changed `base_url` to `base_uri `which stumped me for a moment.

e.g. Original format:

```json
{
    "services": {
        "loco": {
            "params": {
                "key": "xxx",
                "base_url": "https://localise.biz/api",
            }
        }
}
```

e.g. Changed format:

```json
{
   "key": "xxx",
   "base_uri": "https://localise.biz/api",
}
```


From memory (4 years ago!) I think the format was Guzzle-related, but the reality now is that people have that file out there in the wild and I need good cause to change it. I appreciate your format is cleaner, but I'm looking for a better reason.

As it happens my test environment has several service definitions in the same file, which I can't use under the new system.

**Comment by Webonaute** [comment]
Just to mention that all this upgrade and swizzle upgrade is sponsored by UGroupMedia to get rid of outdated libraries. We are happy to share it to the community.

**Comment by supersmile2009** [comment]
Oh, I didn't understand from your first message which config you meant.

Old config format was done in such way because it was Guzzle's ServiceBuilder format, but it makes no sense now since there's no ServiceBuilder in new versions of Guzzle. And even if custom service builder is created to support multiple configs in one file like before, it will still require all projects using this sdk to update their code accordingly to switch to that new service builder. So either way we have a breaking change here.
And I don't think ServiceBuilder is the way most projects use to build their ApiClient anyway. Passing a path to a file... Not an array, not a json, but a path to file - sounds weird and inconvenient to me, no wonder why they dropped that feature in Guzzle.

In the meantime `Loco\Http\ApiClient::factory()` retains compatibility for the most part - you can just pass a `['key' => 'your_api_key']` and you're good to go.
`base_url` was changed to `base_uri` to conform with new guzzle's parameter name, however it's redundant and is only used to override "baseUri" defined in service.json, so this parameter isn't normally needed.

There's a bunch of breaking changes here, so you should tag it as v2.0.0 anyway. I tried to retain compatibility with old version as much as possible, but most of those breaking changes come from guzzle itself, and there's no way to get away from that. Amount of work to upgrade existing projects to use the new version will depend mainly on how many of guzzle-specific features they used and the config is the least concern I believe.

**Comment by timwhitlock** [comment]
@supersmile2009 Thanks. Understood.

@Webonaute Can you explain what you mean my sponsored?

**Comment by supersmile2009** [comment]
@timwhitlock I think what @Webonaute meant was the fact that I wasn't doing it just on bare enthusiasm, but UGroupMedia decided to invest a good deal of my work hours into this upgrade. And decided not only to upgrade features we need, but upgrade everything, including console commands, swizzle package etc. to make it not just another half-broken fork, but release-ready for upstream.

**Comment by timwhitlock** [comment]
I haven't forgotten about this. I've been working on it today.

One things come up so far. Without the StrictCommand, request parameters are no longer validated. I'd like to do this in the same you've done with responses using `validate_request": true`. Looking over the Guzzle Serializer I can't see how it can be done in the same way. i.e. I don't see a method that can be overridden which gets the parameters and the model. Any ideas?

**Comment by supersmile2009** [comment]
StrictCommand was there not for request but for response validation. That's exactly what new `validate_request` does.

Requests are always validated automatically by guzzle-services. It uses `ValidatedDescriptionHandler` class by default, which calls `SchemaValidator::validate()`. Try calling `$client->createTag()` without required `name` parameter and it will throw an exception saying `name` parameter is required.

**Comment by timwhitlock** [comment]
Sorry yes, you're right. I was thinking it used to validate extra (not needed) query parameters too, but checking it now I can see it never did.

**Comment by timwhitlock** [comment]
Thanks for your work on this. 2.0 is now on master branch and will be released shortly.

**Pull request closed without merging**
